// Warning: generated file; your changes could be lost when a new file is generated.
#r @"..\..\FirefoxSync\bin\Release\FirefoxSync.dll"
#r @"..\..\packages\FsCheck.0.9.4.0\lib\net40-Client\FsCheck.dll"
#r @"..\..\packages\FsCheck.Xunit.0.4.1.0\lib\net40-Client\FsCheck.Xunit.dll"
#r @"..\..\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.0.24\lib\net40\Microsoft.Diagnostics.Tracing.EventSource.dll"
#r @"..\..\packages\NUnitTestAdapter.1.0\lib\nunit.core.dll"
#r @"..\..\packages\NUnitTestAdapter.1.0\lib\nunit.core.interfaces.dll"
#r @"..\..\packages\NUnit.2.6.3\lib\nunit.framework.dll"
#r @"..\..\packages\NUnitTestAdapter.1.0\lib\nunit.util.dll"
#r @"..\..\packages\NUnitTestAdapter.1.0\lib\NUnit.VisualStudio.TestAdapter.dll"
#r @"System.dll"
#r @"System.Core.dll"
#r @"System.Numerics.dll"
#r @"..\..\packages\xunit.1.9.2\lib\net20\xunit.dll"
#r @"..\..\..\..\..\..\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Excel\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Excel.dll"